final_model_training:
  # Model selection: 'auto' for best from hyperparameter tuning, or specify: 'random_forest', 'xgboost', 'extra_trees'
  model_selection: 'auto'
  
  # Auto selection criteria when model_selection is 'auto'
  auto_selection:
    metric: 'test_r2'  # Options: 'test_r2', 'cv_score', 'test_rmse', 'test_mae'
    source: 'hyperparameter_tuning'  # Options: 'hyperparameter_tuning', 'basic_training'
  
  # Model-specific configurations
  models:
    random_forest:
      enabled: true
      # Use 'auto' to load best parameters from hyperparameter tuning, or specify custom parameters
      parameters: 'auto'
      # Custom parameters (used when parameters is not 'auto')
      custom_parameters:
        n_estimators: 200
        max_depth: 20
        min_samples_split: 5
        min_samples_leaf: 2
        max_features: 'sqrt'
        bootstrap: true
        random_state: 42
        n_jobs: -1
    
    xgboost:
      enabled: true
      parameters: 'auto'
      custom_parameters:
        n_estimators: 200
        learning_rate: 0.1
        max_depth: 6
        min_child_weight: 3
        subsample: 0.8
        colsample_bytree: 0.8
        gamma: 0
        reg_alpha: 0
        reg_lambda: 1
        random_state: 42
    
    extra_trees:
      enabled: true
      parameters: 'auto'
      custom_parameters:
        n_estimators: 200
        max_depth: 20
        min_samples_split: 5
        min_samples_leaf: 2
        max_features: 'sqrt'
        bootstrap: false
        random_state: 42
        n_jobs: -1
  
  # Training settings
  training:
    # Cross-validation settings for final evaluation
    cv_folds: 5
    cv_scoring: 'r2'
    
    # Feature importance analysis
    feature_importance: true
    
    # Model persistence
    save_model: true
    model_format: 'joblib'  # Options: 'joblib', 'pickle'
    
    # Evaluation metrics to compute
    metrics:
      - 'r2_score'
      - 'mean_squared_error'
      - 'mean_absolute_error'
      - 'explained_variance_score'
      - 'max_error'
      - 'median_absolute_error'
  
  # Results and output settings
  results:
    # Directory structure
    create_sample_directory: true
    
    # Reports to generate
    generate_reports:
      - 'performance_summary'
      - 'detailed_metrics'
      - 'feature_importance'
      - 'prediction_analysis'
      - 'model_comparison'
    
    # Visualization settings (if matplotlib is available)
    generate_plots: true
    plot_types:
      - 'prediction_vs_actual'
      - 'residuals'
      - 'feature_importance'
      - 'learning_curves'
    
    # Export formats
    export_formats:
      - 'txt'
      - 'csv'
      - 'json'
  
  # Advanced settings
  advanced:
    # Memory optimization
    low_memory_mode: false
    
    # Reproducibility
    random_state: 42
    
    # Parallel processing
    n_jobs: -1
    
    # Verbose output
    verbose: true
    
    # Performance monitoring
    monitor_training_time: true
    monitor_memory_usage: false
